### ISSUE TITLE
I am not able to login to host (ubuntu-c) as ansible and the password of password

### ISSUE THREAD

**Issue by Rishaan56** [spurin/diveintoansible#10]
Can you please tell me what is the reason and issue.I am attaching my .env file.
I am running on Windows 10 machine.
[myenv.zip](https://github.com/spurin/diveintoansible/files/6797156/myenv.zip)

Thanks
Pandu G

**Comment by Rishaan56** [comment]
Hi James,

Can you please help with this issue to login to lab.

Thanks
Pandu G

**Comment by Rishaan56** [comment]
Hi,
Thank you.I did changed the config values as per README doc in my machine and I still have the same issue.

# Shared config volume
CONFIG=/users/rishaan/diveintoansible-lab/config

# Shared home directories
ANSIBLE_HOME=/users/rishaan/diveintoansible-lab/ansible_home

Please let me know , if some thing I am missing.

**Comment by akc5247** [comment]
@Rishaan56 - yes, you need to add /host_mnt/c in front of both like Rich mentioned above

so basically, 

CONFIG=/host_mnt/c/users/rishaan/diveintoansible-lab/config

**Comment by Rishaan56** [comment]
ok..Thank you so much..

**Comment by spurin** [comment]
Thanks @akc5247, appreciate your help on this.  @Rishaan56 if theres still any problems please re-open this issue.  Hope you're enjoying the course!
