### ISSUE TITLE
Ansible Playbooks, Deep Dive/Looping/11

### ISSUE THREAD

**Issue by calvincantrell** [spurin/diveintoansible#18]
the ansible code  password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits,punctuation') | password_hash('sha512') }}"  creates the password for the users, but how would you give that to them?  you dont know what it generated. it would be better to change this to a real world example of one where the user would be able to receive their password so they could login.  but since you are using ssh keys, they dont have to worry, but what if ssh-keys were broken?

**Comment by calvincantrell** [comment]
You are right. I have since found a way to store into variable. I'm new to Ansible but Im learning and your course is by far the best!
Basically it equates to generating password separately storing that in variable and then using that variable  in python -c command to set password and you could optionally store the generated password in a vault like ansible vault and email the user their password too.  I have not finished course, so did not get to the ansible vault part yet :) I only learned about it from another colleague.

**Comment by calvincantrell** [comment]
Sorry James , I also meant to say you can close the issue or mark it resovled.

**Comment by spurin** [comment]
Thanks @calvincantrell appreciate the discussion and understanding!  Thanks for closing and I hope you continue to enjoy the course.  The vault section is covered in great detail and we do some stuff that maybe your colleagues will like, in particular how to use multiple names vaults which isn't covered that well, in the docs
