### ISSUE TITLE
AWS with Ansible

### ISSUE THREAD

**Issue by ktinthecloud** [spurin/diveintoansible#21]
Getting the following error when attempting to run the `ec2_playbook.yaml ` in the AWS with Ansible section:

[DEPRECATION WARNING]: amazon.aws.ec2 has been deprecated. The ec2 module is based upon a deprecated version of the AWS SDKs and is deprecated in favor of the ec2_instance module. Please update your 
tasks. This feature will be removed from amazon.aws in version 4.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by ktinthecloud** [comment]
The playbook still runs fine.  Closing issue.

**Comment by spurin** [comment]
Thanks!

For now, would you try the deprecation_warnings=False in the ansible.cfg and let me know how you get on.

Hopefully this will be sufficient to at least continue the lesson through to completion.

I’m going to look into updating this lecture to the latest version/approach and will keep this issue open until it’s done.


Best Regards


James Spurin
