### ISSUE TITLE
[emerg] 1#1: host not found in upstream "ubuntu1" in /etc/nginx/conf.d/default.conf:45

### ISSUE THREAD

**Issue by pveera77** [spurin/diveintoansible#22]
I get the following error when running **docker-compose up**

Attaching to centos1, centos2, centos3, docker, portal, ubuntu-c, ubuntu1, ubuntu2, ubuntu3
ubuntu3 exited with code 255
ubuntu-c exited with code 255
ubuntu2 exited with code 255
ubuntu1 exited with code 255
portal    | 2022/10/12 21:32:48 [emerg] 1#1: host not found in upstream "ubuntu1" in /etc/nginx/conf.d/default.conf:45

**Comment by spurin** [comment]
Hi @pveera77 

Could you tell me more about the environment you're running this in?

Is it Windows with WSL by any chance?

In the meantime, while we troubleshoot please use the free web environment at https://diveinto.com/p/playground
