### ISSUE TITLE
unable to ping centos1 on port 2222 from Ubuntu-c

### ISSUE THREAD

**Issue by pixelet** [spurin/diveintoansible#26]
Hello,
      I installed the extension from Docker Desktop extensions, also noticed that for first few folder 01 -03 I had to use -k option for Centos machine to be able to ping them.  Not sure if I missed something in my initial setup but it should be plug-n-play.

Thank you

**Comment by spurin** [comment]
Hi @pixelet 

Connectivity via ssh to port 2222 is managed within the docker-compose.ya file for centos1.

If you search for centos1 in the file you'll see 2 images that can be used for this instance, the default runs on 22, the other port 2222

You'll just need to restart the lab after making changes 👍

**Comment by spurin** [comment]
Ahh wait, you mentioned the Docker Desktop extension.

Leave this open, I'll make some changes to accommodate this given, that the compose file is not easy to edit, when ran as an extension

**Comment by pixelet** [comment]
Thank you James,
     I removed the extension and reinstalled from Docker Desktop again and I see the same issue.  I did install the sshpass tool and re-ran folder '10' exercise.  Following it my output.

ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/10$ ansible all -m ping -o -k
SSH password: 
centos1 | UNREACHABLE!: Failed to connect to the host via ssh: ssh: connect to host centos1 port 2222: Connection refused
ubuntu-c | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
ubuntu1 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
ubuntu2 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
centos2 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"},"changed": false,"ping": "pong"}
centos3 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"},"changed": false,"ping": "pong"}
ubuntu3 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/10$ pwd
/home/ansible/diveintoansible/Ansible Architecture and Design/Inventories/10

thanks

**Comment by spurin** [comment]
Hi @pixelet 

During the course, at one stage we swap the image used in the lab for centos1 to another image that uses port 2222 for ssh instead of port 22

This is why it's failing, as this step hasn't been done.

Unfortunately, editing the docker-compose.yaml file is more challenging in the extension as it's hidden away.

Quickest fix will be to edit the hosts file and to change 2222 to 22

I will look into seeing if there is another way this can be edited in the Docker Desktop Extension

**Comment by pixelet** [comment]
Thank you James,
         Yeah, I had already tried port 22 and that worked fine.  I just wanted to make sure I wasn't missing anything on my end, whether I missed a step or some other issue.  Other then that this exercise works great and thank you for your quick response.
Best Regards
