### ISSUE TITLE
sshd is not lising on port 2222

### ISSUE THREAD

**Issue by shail8989** [spurin/diveintoansible#3]
during the setup of ansible inventories , i have changed the sshd port - 2222 in compose.yaml and start it 

ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/07$ ls
ansible.cfg  hosts
ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/07$ cat hosts 
[centos]
centos1:2222 ansible_user=root
centos2 ansible_user=root
centos3 ansible_user=root

[ubuntu]
ubuntu1 ansible_become=true ansible_become_pass=password
ubuntu2 ansible_become=true ansible_become_pass=password
ubuntu3 ansible_become=true ansible_become_pass=password
ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/07$ ansible all -m ping -o 
centos1 | UNREACHABLE!: Failed to connect to the host via ssh: Warning: the ECDSA host key for 'centos1' differs from the key for the IP address '172.18.0.5'
Offending key for IP in /home/ansible/.ssh/known_hosts:10
Matching host key in /home/ansible/.ssh/known_hosts:1
root@centos1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
ubuntu1 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
ubuntu2 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
ubuntu3 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
centos3 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"},"changed": false,"ping": "pong"}
centos2 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"},"changed": false,"ping": "pong"}
-----------------------------------------------------------------------------------------------------------------------------

i tried also after removing the known_hosts and tried after that but it said again that permission denied as below...

nsible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/07$ rm -rf /home/ansible/.ssh/known_hosts 
ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/07$ ansible centos1 -m ping -o
centos1 | UNREACHABLE!: Failed to connect to the host via ssh: Warning: Permanently added '[centos1]:2222,[172.18.0.5]:2222' (ECDSA) to the list of known hosts.
root@centos1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/07$ ssh centos1:2222
ssh: Could not resolve hostname centos1:2222: Name or service not known

ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/07$ ssh [centos1]:2222
ssh: Could not resolve hostname [centos1]:2222: Name or service not known

**Comment by spurin** [comment]
Hi @shail8989,

Are you following the video course for this or are you just going through the github repo's by yourself (no issues if so, just to give me a better understanding :-) ).

In the video lecture, it highlights that you need to update the docker-compose.yaml file, swapping the image to one that has been configured to listen on port 2222 for sshd, i.e. Toggle these lines, hashing the one, and unhashing the other -

```
    image: spurin/diveintoansible:centos
    #image: spurin/diveintoansible:centos-sshd-2222
```

```
     - ${CENTOS1_PORT_SSHD}:22
     #- ${CENTOS1_PORT_SSHD}:2222
```

Then, you need to do a ctrl-c on your running lab environment and a docker-compose up, it should then recreate centos1 with the new image.

In your case, as you don't have the persistent home directories, you should also recreate the trusted ssh relationships from ubuntu-c by doing -

```
ssh-copy-id ansible@centos1
ssh-copy-id root@centos1
```

Good luck

**Comment by shail8989** [comment]
hi James,
yes i am following the videos and i have updated my docker-compose.yaml file as below and did the same CTRL+C and start it again . 

  centos1:
    hostname: centos1
    container_name: centos1
    #image: spurin/diveintoansible:centos
    image: spurin/diveintoansible:centos-sshd-2222
    ports: 
    #- ${CENTOS1_PORT_SSHD}:22
     - ${CENTOS1_PORT_SSHD}:2222
     - ${CENTOS1_PORT_TTYD}:7681
    privileged: true
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
    networks:
     - diveinto.io

------------------------------------------------
also i copied the ssh-copy-id to centos1 like below and it gives this error.

ansible@ubuntu-c:~$ ssh-copy-id ansible@centos1
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: ERROR: ssh: connect to host centos1 port 22: Connection refused

ansible@ubuntu-c:~$ ssh-copy-id root@centos1
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: ERROR: ssh: connect to host centos1 port 22: Connection refused

ansible@ubuntu-c:~$ 
-------------------------------------------------------
I also tried generating new keys and send again by loop to all hosts but it is still not listing on 2222.

ansible@ubuntu-c:~$ ssh root@centos1
ssh: connect to host centos1 port 22: Connection refused

ansible@ubuntu-c:~$ ssh ansible@centos1
ssh: connect to host centos1 port 22: Connection refused

ansible@ubuntu-c:~$ ping centos1
PING centos1 (172.18.0.4) 56(84) bytes of data.
64 bytes from centos1.diveinto.io (172.18.0.4): icmp_seq=1 ttl=64 time=0.060 ms
64 bytes from centos1.diveinto.io (172.18.0.4): icmp_seq=2 ttl=64 time=0.173 ms
^C
--- centos1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1055ms
rtt min/avg/max/mdev = 0.060/0.116/0.173/0.056 ms

ansible@ubuntu-c:~$ ssh centos2
Last login: Tue Jan 12 04:52:04 2021 from 172.18.0.9
[ansible@centos2 ~]$ exit
logout
Connection to centos2 closed.

**Comment by bonsi** [comment]
Now your SSHD server daemon _is_ running on port 2222 on centos1 but now you try to connect to it using port 22. You'd have to tell SSH to use port 2222 (it defaults to 22 as can be observed above) by using the following format: `ssh user@host -p port` and `ssh-copy-id user@host -p port`.

**Comment by spurin** [comment]
Thanks @bonsi :-)

@shail8989 - specifically, in your case, the following command will fix the issue you're experiencing (from ubuntu-c) -

```
ssh-copy-id ansible@centos1 -p 2222
```

Once the key has been copied, you should be able to then ssh specifying the port -

```
ssh centos1 -p 2222
```

From then onwards, you should just be able to continue with the course as the inventories going forward, use 2222

Best Regards


James Spurin

**Comment by shail8989** [comment]
thanks @spurin , I understand it . i am able to connect by 2222 now

**Comment by spurin** [comment]
Perfect, closing the issue
