### ISSUE TITLE
Unable to connect to centos (all)

### ISSUE THREAD

**Issue by DanielaSofia** [spurin/diveintoansible#32]
Hi,
I'm currently in exercice 4 for inventory fiiles where we connect as root to the centos
`ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/04$ cat hosts 
[centos]
centos1 ansible_user=root
centos2 ansible_user=root
centos3 ansible_user=root

[ubuntu]
ubuntu1
ubuntu2
ubuntu3
ansible@ubuntu-c:~/diveintoansible/Ansible Architecture and Design/Inventories/04$ `

and it always five me root errors like:
`centos1 | UNREACHABLE!: Failed to connect to the host via ssh: root@centos1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
centos2 | UNREACHABLE!: Failed to connect to the host via ssh: root@centos2: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
centos3 | UNREACHABLE!: Failed to connect to the host via ssh: root@centos3: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
ubuntu2 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
ubuntu3 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}
ubuntu1 | SUCCESS => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"},"changed": false,"ping": "pong"}`

and when I copy the publick key via ssh to rrot this happens: `ssh-copy-id -p 2222 root@centos1
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@centos1's password: 
bash: /root/.bashrc: Permission denied
mkdir: cannot create directory ‘.ssh’: Permission denied`

Can you help me?

**Comment by j4v3l** [comment]
I had this issue earlier, I was able to solve it with the help of [#89](https://github.com/spurin/diveintoansible-lab/issues/89).

Do the following steps from within "Ubuntu-c"

Step 1:

`sudo apt-get update && sudo apt-get install sshpass`

Step 2:

`sudo cat  > ~/.ssh/password` then type "password" then ctrl + D

Step 3:

`for user in ansible root; do   for os in ubuntu centos;   do     for instance in 1 2 3;     do       sshpass -f password.txt ssh-copy-id -o StrictHostKeyChecking=no ${user}@${os}${instance};     done;   done; done`

**Comment by spurin** [comment]
Hi @DanielaSofia 

If you're still having this problem, can you please tell me about your environment setup.  If you're running on Windows, Linux, Mac and if you're using a subsystem like WSL in the case of windows.

Most of the time when I see this issue it's with Windows and WSL.  If you can confirm, if the issue still persists after @j4v3l kind feedback, let me know and we'll explore this option for you.

Thanks


James

**Comment by DanielaSofia** [comment]
Hi :)
I've tried the @j4v3l answer but it still doesnt work.
I use Linux (Ubuntu 20.04).
I'm guessing the centos for me has some kind of permissions issue but I cant do anything using sudo on centos always gives me permissions issues like operation 'ls' in root directory being root.

**Comment by spurin** [comment]
Thanks @DanielaSofia 

To elaborate on the troubleshooting of this, for data persistence, so that your Ansible and root user home directories are retained on each of the lab hosts if you destroy and recreate the lab (as you may have created playbooks you want to keep).

In the docker-compose.yaml file, you'll see that /home is a volume mount to that of a local folder.

Sometimes, someone will download and configure the diveintoansible-lab directory as their own user, so for example daniela, then they will run the docker compose up as another user, for example root.

This then, this gets cross permission problems when the lab runs as the volume mount permissions do not tally up.

Could you share where the lab folder is please and how the docker compose up, is being run (with what user).  Can then guide on best steps to get this on track 👍

**Comment by DanielaSofia** [comment]
The lab folder in in my home directory and I am using docker compose up with my user(not root), also tried to run using docker-desktop and its the same thing.

**Comment by DanielaSofia** [comment]
Well I tried to delete the lab and clonet it again and now it seems to be working :)

**Comment by spurin** [comment]
Brilliant,

@DanielaSofia this was going to be my next suggestion.  The docker permissions system is quite complex under the covers and when I encounter this issue on WSL under Windows, the only way of clearing it seems to be by -

1. Deleting the running containers
2. Deleting the volume mount directories
3. Restarting the lab

Glad you got it resolved and hope you enjoy the rest of the course!  Kudos as well for using Ubuntu as your main desktop 😁🚀

**Comment by spurin** [comment]
Closing this issue, thanks all
