### ISSUE TITLE
ansible@ubuntu1: Permission denied (publickey,password).

### ISSUE THREAD

**Issue by Nedaysr** [spurin/diveintoansible#37]
@spurin Hello Mr Spurin, I hope, you are doing well.
 I am learning Ansible by Udemy courses. In the Configuration SSH Conectivity between hosts part, when Im using cmd ssh ubuntu1, It doesnt accept the password and i got the error permission denied. Could you please guid me about that. 
Thank you so much.

<img width="543" alt="ssh ubuntu1" src="https://github.com/spurin/diveintoansible/assets/140532506/5ec501f4-2716-4a26-9ab3-14497c29bb17">

**Comment by spurin** [comment]
Hi @Nedaysr 

Thanks so much for reaching out, does it accept the default password of password?

**Comment by Nedaysr** [comment]
@spurin it accepted "password". I thaught that I should enter a new password. Thank you so much :)
