### ISSUE TITLE
Add support for rancher desktop

### ISSUE THREAD

**Issue by calebreduskyndryl** [spurin/diveintoansible#38]
Add support for rancher desktop currently the default ownership and permissions for the lab container volumes are not correct, preventing password-less public key login to the lab containers [ubuntu1-3 & centos1-3] via ssh.

A workaround is to, on all 6 containers un-comment the `StrictMode` and `PubkeyAuthentication` lines; then set `StrictMode no` in the `/etc/ssh/sshd_config` file. Next run the `systemctl restart sshd`, command.

A better solution and likely fix is to figure out a way where the ansible user home directory and all of its subdirectories are owned by the `ansible` user and group. Instead of as it is now where the 501 user and `dailout` group own it.

![image](https://github.com/spurin/diveintoansible/assets/154255176/bd31cac3-fe8b-490d-91bf-54cbf997bd31)

**Comment by spurin** [comment]
HI @calebreduskyndryl - I'm open to working on support for different platforms with people on a best efforts basis however, for maintenance purposes I prefer to limit the options to Docker Desktop, Docker and Cloud Shell.

If you wish to make a branch off the main repo with steps as per the Podman example, I'd be happy to work on this with you.

In the meantime, closing this for now.
