### ISSUE TITLE
https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html not working

### ISSUE THREAD

**Issue by juergenschubert** [spurin/diveintoansible#5]
Link in your documentation in "Ansible Playbooks, Breakdown of Sections".
found instead:
https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html

**Comment by spurin** [comment]
Thanks @juergenschubert appreciate you letting me know this.  I will update this accordingly and get a new video out.

**Comment by spurin** [comment]
Hi @juergenschubert 

![image](https://user-images.githubusercontent.com/850464/139533236-7443baae-de3f-4cf4-b33b-920f4213360b.png)

Thanks for raising this.  Coincidently the old link now works, but, I updated accordingly.  Have also taken this opportunity to add QR codes for ease to each of the links.  Therefore, if you're watching on one device and have another device free, i.e. a phone, you can quickly scan the QR code for ease :-)

Thanks for raising this.  This is in 4.2 and currently, I'm just wrapping up the refreshed Section 4.  When it's on Udemy I'll close the issue.

- James

**Comment by spurin** [comment]
Resolved, updates are on Udemy 🎉
