### ISSUE TITLE
Cannot Create Docker Container due to Python mismatch

### ISSUE THREAD

**Issue by zdimitris** [spurin/diveintoansible#7]
Hi @spurin 
I have 2 Ubuntu 20.04 instances on AWS and I try to Create a Container from an Image I have already created on the Managed node. The Python is 3.8 and when I run the playbook:
---
- name: Create a sample Container
  hosts: slave1
  become: true
  
  tasks:
    - name: Create a sample Container from an image in the current directory
      docker_container:
        name: test
        image: node

I get the error:
fatal: [client1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on ip-<MY IP>'s Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}

I have configured the inventory on the master node as follows:

[production]
client1 ansible_ssh_host=<AWS IP1>
client2 ansible_ssh_host=<AWS IP2>

[production:vars]
ansible_python_interpreter=/usr/bin/python3

I cannot rid of this error. Without being installed pip it didn't work. I installed pip although I had pip3, but again nothing!
Please, any suggestion?

**Comment by spurin** [comment]
Hi @zdimitris 

Apologies for the late response to this.  If you're still troubled by this, re-open the issue and I'll take a look with you

Best Regards,


James
